### ISSUE TITLE
Selecting from dropdown does not update ng-model

### ISSUE THREAD

**Issue by MarcelEdward2** [hardy12994/ng5-auto-complete#3]
I have got an [(ngModel)]="tags" wich gets updated when I type in text in the textbox

When I choose an option from the dropdown generated by ng5-auto-complete then it is filled in the input box but somehow the ngModel is not updated, I was wondering why ?

**Comment by hardeep-bit** [comment]
Hi @MarcelEdward2 , Sorry for Late Reply - I want confirm one thing that `tags` which you have set in the `[(ngModel)] (` as `[(ngModel)]="tags"` ) , Is that they are coming form an API or their any Async call then  you update the tags field with ngModel  ?

**Comment by yashrs** [comment]
I am getting the same error. In my case, it's something like this:-
`            <input type="text"  value="Dub"
             [(ngModel)]="search_city"
            placeholder="City Name" 
            id="list" 
            [ng5-auto-complete]="suggestions"
            filterName="city"
             (ngModelChange)="ajaxCity($event);"
            no-record-text="No Records Found!" />
`

Neither the ngModel that is search gets updated... nor does the ajaxCity method get called when we select something from the dropdown.

**Comment by hardeep-bit** [comment]
@yashrs  Please tell the version of your angular ?
